<!DOCTYPE html>
<html>
<head>
    <title>BOOKTREE</title>
    <link rel="icon" type="image/x-icon" href="/static/photo/tree1.ico">
    <link type="text/css" rel="stylesheet" href="/static/css/adminPage.css"/>
    <link type="text/css" rel="stylesheet" href="/static/css/styles.css"/>
</head>
<body>
<header>
    <div class="container">
        <img src="/static/photo/tree2.png" height="50px">
        <h3>BOOKTREE</h3>
        <ul>
            <li><a href="/admin">Пользователи</a></li>
            <li><a href="/product/allProducts">Все товары</a></li>
            <li><a href="/addProducts">Добавление товаров</a></li>
        </ul>
    </div>
</header>
<div class="Menu">
<ul >
    <li ><a  href="/admin">Пользователи</a></li>
    <li ><a href="/product/allProducts">Все товары</a></li>
    <li ><a href="/addProducts">Добавление товаров</a></li>
</ul>
</div>
</body>
</html>